name: one_five_one_ten
description: A new Flutter project for personal investment tracking.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 锁定 Isar 版本
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  
  path_provider: ^2.0.11
  flutter_riverpod: ^2.4.9
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  http: ^1.1.0 
  gbk_codec: ^0.4.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

  # 锁定 Isar Generator 和 Build Runner 的版本，与 Isar 库匹配
  isar_generator: 3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true