name: one_five_one_ten
description: A new Flutter project for personal investment tracking.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Isar 数据库核心库
  isar: ^3.1.0+1
  # Isar Flutter 专用库
  isar_flutter_libs: ^3.1.0+1
  # 用于获取文件系统路径，Isar初始化时需要
  path_provider: ^2.0.11
  
  # 状态管理库 Riverpod
  flutter_riverpod: ^2.4.9

  # 其他UI辅助库
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter 代码规范
  flutter_lints: ^2.0.0

  # Isar 代码生成器
  isar_generator: ^3.1.0+1
  # Flutter 项目构建工具
  build_runner: ^2.4.6

flutter:
  uses-material-design: true